apiVersion: v1
kind: Pod
metadata:
  name: taint
  labels:
    purpose: "taint-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx-container
    image: nginx
